'use client';
import {useEffect,useRef,useState} from 'react';
import type {Trip} from '@/lib/trip';
import 'leaflet/dist/leaflet.css';
import 'leaflet.markercluster/dist/MarkerCluster.css';
import 'leaflet.markercluster/dist/MarkerCluster.Default.css';
export default function TripMap({plan,visits,day,selected,onSelect,overview=false}:{plan:Trip;visits:any[];day:any;selected:any;onSelect:(v:any)=>void;overview?:boolean}){
 const node=useRef<HTMLDivElement>(null),map=useRef<any>(null),lib=useRef<any>(null),layer=useRef<any>(null),callback=useRef(onSelect);callback.current=onSelect;const [ready,setReady]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;import('leaflet').then(async m=>{const L=m.default;(window as any).L=L;await import('leaflet.markercluster');if(!live||!node.current)return;lib.current=L;map.current=L.map(node.current,{scrollWheelZoom:false,zoomControl:false}).setView([47,19],4);L.control.zoom({position:'topright'}).addTo(map.current);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map.current).on('tileerror',()=>setError('Картографическая подложка временно недоступна. Точки и расписание остаются доступны.'));layer.current=L.layerGroup().addTo(map.current);const ro=new ResizeObserver(()=>map.current?.invalidateSize());ro.observe(node.current);(map.current as any)._resizeObserver=ro;setReady(true)}).catch(()=>setError('Не удалось загрузить карту. Все места доступны в расписании.'));return()=>{live=false;map.current?._resizeObserver?.disconnect();map.current?.remove();map.current=null}},[]);
 useEffect(()=>{if(!ready||!map.current)return;const L=lib.current;layer.current.clearLayers();const cluster=L.markerClusterGroup({maxClusterRadius:35,showCoverageOnHover:false,spiderfyOnMaxZoom:true,disableClusteringAtZoom:17});const bounds:any[]=[];const activeDate=day?.date;
 const lines=plan.transfers.filter(t=>overview||!day||t.date===activeDate);for(const t of lines){const f=plan.cities[t.from],to=plan.cities[t.to];if(!f||!to)continue;L.polyline([[f[1],f[2]],[to[1],to[2]]],{color:t.mode==='flight'?'#c68138':t.mode==='unknown'?'#7a7f89':'#217785',weight:2.5,opacity:.75,dashArray:t.mode==='flight'?'3 8':t.mode==='unknown'?'2 10':'10 5'}).bindTooltip((t.mode==='flight'?'Перелёт':t.mode==='train'?'Поезд':t.mode==='bus'?'Автобус':'Транспорт уточняется')+' · '+t.date+' · схематично').addTo(layer.current);if(overview)bounds.push([f[1],f[2]],[to[1],to[2]])}
 for(const v of visits){const p=plan.places.find(x=>x.id===v.placeId);if(!p)continue;const coords=[p.lat,p.lng];bounds.push(coords);const symbol:Record<string,string>={sight:'◆',rest:'♧',food:'◉',hotel:'▰',airport:'✈',station:'▤'};const marker=L.marker(coords,{icon:L.divIcon({html:'<span class="pin '+(selected?.id===v.id?'selected':'')+' '+v.category+'">'+(symbol[v.category]||'•')+'</span>',className:'trip-marker',iconSize:[34,34],iconAnchor:[17,17]})});const tip=document.createElement('span');tip.textContent=v.title+(v.start?' · '+v.start:'');marker.bindTooltip(tip);marker.on('click',()=>callback.current(v));cluster.addLayer(marker)}layer.current.addLayer(cluster);
 if(selected){const p=plan.places.find(x=>x.id===selected.placeId);if(p)map.current.flyTo([p.lat,p.lng],p.category==='city'?11:15,{duration:.8})}else if(bounds.length)map.current.flyToBounds(bounds,{padding:[55,55],maxZoom:overview?5:13,duration:.8});else if(day){const c=plan.cities[day.city];map.current.flyTo([c[1],c[2]],11,{duration:.8})}
 },[ready,plan,visits,day,selected,overview]);
 return <div className="mapwrap"><div ref={node} className="map" aria-label="Интерактивная карта маршрута"/><div className="map-label"><span className="live-dot"/>{overview?'Весь маршрут':day?.title||'Маршрут'}<small>ЛИНИИ СХЕМАТИЧНЫЕ</small></div><div className="map-legend"><span>◆ Место</span><span>▰ Жильё</span><span>◉ Еда</span><span>✈ Аэропорт</span><span>▤ Вокзал / переезд</span><span>♧ Отдых</span><span className="air-line">Перелёт</span><span className="rail-line">Поезд</span><span>··· Транспорт уточняется</span></div>{error&&<p className="map-error" role="status">{error}</p>}</div>
}
