export type Trip = { schemaVersion:number; version:string; importedAt:string; sourceDocument:string; sourceTabs:any[]; family:any; cities:Record<string,any[]>; days:any[]; places:any[]; visits:any[]; transfers:any[]; expenses:any[]; checks:any[]; issues:string[] };
export type Personal = { visits:Record<string,{note?:string;status?:string;favorite?:boolean;start?:string;end?:string;price?:number|null}>; checks:Record<string,boolean> };
export const emptyPersonal:Personal={visits:{},checks:{}};
export const statusNames:Record<string,string>={planned:'В плане',booked:'Забронировано',visited:'Посетили',skip:'Пропустить'};
export const categoryNames:Record<string,string>={sight:'Места',food:'Еда',hotel:'Жильё',airport:'Аэропорты',station:'Переезды',rest:'Отдых',city:'Города'};
export const expenseNames:Record<string,string>={flights:'Перелёты',lodging:'Жильё',transport:'Транспорт',tickets:'Билеты',food:'Питание',other:'Прочее'};
export const money=(n:number,c='EUR')=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:c,maximumFractionDigits:2}).format(n);
export const dateLabel=(d:string)=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
export function validateTrip(x:any):asserts x is Trip{
 if(!x||x.schemaVersion!==1||typeof x.version!=='string'||!x.cities||typeof x.cities!=='object')throw Error('Нужен файл маршрута Европа 2026, версия формата 1.');
 if(typeof x.importedAt!=='string'||!Number.isFinite(Date.parse(x.importedAt))||typeof x.sourceDocument!=='string'||!Array.isArray(x.sourceTabs))throw Error('Отсутствует дата импорта или источник');
 for(const c of Object.values(x.cities) as any[])if(!Array.isArray(c)||typeof c[0]!=='string'||!Number.isFinite(c[1])||!Number.isFinite(c[2]))throw Error('Некорректный справочник городов');
 for(const key of ['days','places','visits','transfers','expenses','checks','issues'])if(!Array.isArray(x[key]))throw Error('В файле отсутствует раздел '+key);
 for(const key of ['days','places','visits','transfers','expenses','checks']){const ids=new Set();for(const v of x[key]){if(typeof v.id!=='string'||!v.id||ids.has(v.id))throw Error('Пустой или повторяющийся идентификатор в '+key);ids.add(v.id)}}
 for(const key of ['days','places','visits','expenses'] as const)for(const v of x[key])if(typeof v.title!=='string'||v.title.length>1000)throw Error('Некорректное название');
 for(const v of x.visits)if(typeof v.description!=='string')throw Error('Нет описания посещения');
 for(const c of x.checks)if(typeof c.text!=='string')throw Error('Некорректный список подготовки');
 for(const issue of x.issues)if(typeof issue!=='string')throw Error('Некорректное замечание');
 for(const t of x.transfers)if(!x.cities[t.from]||!x.cities[t.to]||typeof t.date!=='string')throw Error('Некорректный переезд');
 const days=new Set(x.days.map((d:any)=>d.id)),places=new Set(x.places.map((p:any)=>p.id));
 for(const d of x.days)if(!/^2026-\d{2}-\d{2}$/.test(d.date)||!x.cities[d.city])throw Error('Некорректная дата или город дня');
 for(const p of x.places)if(!Number.isFinite(p.lat)||Math.abs(p.lat)>90||!Number.isFinite(p.lng)||Math.abs(p.lng)>180||!x.cities[p.city])throw Error('Некорректные координаты места');
 for(const v of x.visits){if(!days.has(v.dayId)||!places.has(v.placeId)||!statusNames[v.status]||!categoryNames[v.category])throw Error('Посещение ссылается на неизвестный день, место или статус');for(const k of ['start','end'])if(v[k]&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(v[k]))throw Error('Некорректное время');}
 for(const e of x.expenses)if((e.amount!==null&&(!Number.isFinite(e.amount)||e.amount<0))||!['EUR','RUB','AMD','TRY','USD'].includes(e.currency)||!['paid','planned','estimate','unknown'].includes(e.status)||!expenseNames[e.category])throw Error('Некорректный расход');
 if(JSON.stringify(x).length>2000000)throw Error('Файл маршрута слишком большой');
}
export function validatePersonal(x:any):asserts x is Personal{if(!x?.visits||!x?.checks)throw Error('Резервная копия не содержит личных данных');for(const v of Object.values(x.visits) as any[]){if(v.status&&!statusNames[v.status])throw Error('Неверный статус в копии');if(v.note&&typeof v.note!=='string')throw Error('Неверная заметка');for(const k of ['start','end'])if(v[k]&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(v[k]))throw Error('Неверное время');if(v.price!=null&&(!Number.isFinite(v.price)||v.price<0))throw Error('Неверная цена');}}
export function comparePlans(old:Trip,next:Trip,personal:Personal){const changes:any[]=[];for(const key of ['days','places','visits','transfers','expenses','checks'] as const){const before=new Map(old[key].map((x:any)=>[x.id,x])),after=new Map(next[key].map((x:any)=>[x.id,x]));for(const [id,n]of after){const o=before.get(id);if(!o)changes.push({kind:'Добавлено',section:key,id,title:n.title||n.text||id});else {const fields=Object.keys(n).filter(k=>JSON.stringify(o[k])!==JSON.stringify(n[k]));if(fields.length)changes.push({kind:'Изменено',section:key,id,title:n.title||n.text||id,fields,old:o,next:n,conflict:key==='visits'&&fields.some(k=>Object.hasOwn(personal.visits[id]||{},k))});}}for(const [id,o]of before)if(!after.has(id))changes.push({kind:'Удалено',section:key,id,title:o.title||o.text||id,conflict:key==='visits'&&!!personal.visits[id]});}return changes;}
export function mergePlan(old:Trip,next:Trip){validateTrip(next);return {...next,places:next.places.map(p=>{const prev=old.places.find(x=>x.id===p.id);return {...p,photo:prev?.photo||p.photo}})};}
export function duration(start:string|null,end:string|null){if(!start||!end)return null;const m=(s:string)=>Number(s.slice(0,2))*60+Number(s.slice(3));return (m(end)-m(start)+1440)%1440;}
export function warnings(visits:any[]){const notes:string[]=[];const timed=visits.filter(v=>v.start&&v.end&&!v.optional&&v.status!=='skip').sort((a,b)=>a.start.localeCompare(b.start));for(let i=1;i<timed.length;i++){if(timed[i-1].end>timed[i].start&&timed[i-1].end>timed[i-1].start)notes.push('Пересечение: '+timed[i-1].title+' / '+timed[i].title)}const active=timed.filter(v=>!['rest','hotel','food'].includes(v.category));if(active.reduce((s,v)=>s+(duration(v.start,v.end)||0),0)>480)notes.push('Более 8 часов активной программы. Оставьте время для отдыха.');return notes;}
export function totals(expenses:any[],includeOptional=false){const sums:Record<string,number>={},states:Record<string,Record<string,number>>={paid:{},planned:{},estimate:{}};let unknown=0;for(const e of expenses){if(e.optional&&!includeOptional)continue;if(e.amount===null){unknown++;continue;}sums[e.currency]=(sums[e.currency]||0)+e.amount;const group=states[e.status]||states.estimate;group[e.currency]=(group[e.currency]||0)+e.amount;}return {sums,states,unknown};}
export function demoUpdate(plan:Trip){const base=structuredClone(plan),next=structuredClone(plan);const v=next.visits.find(x=>x.placeId==='nemo')!;const oldTime=v.start;v.start='12:30';const p=next.places.find(x=>x.id==='nemo')!;base.places.find(x=>x.id==='nemo')!.photo='amsterdam';const personal:Personal={visits:{[v.id]:{note:'Взять воду и сделать паузу на крыше',favorite:true}},checks:{}};next.places.push({...p,id:'demo-new-place',title:'Новое место · демонстрация',photo:null});next.visits.push({...v,id:'demo-new-visit',placeId:'demo-new-place',title:'Новое место · демонстрация',start:'16:30',end:'17:00'});const merged=mergePlan(base,next);return {oldTime,newTime:merged.visits.find(x=>x.id===v.id).start,added:merged.visits.length-base.visits.length,photoSaved:merged.places.find(x=>x.id==='nemo').photo==='amsterdam',noteSaved:personal.visits[v.id].note,changes:comparePlans(base,next,personal)};}
export function safeUrl(s:string){try {const u=new URL(s);return u.protocol==='https:'?u.href:undefined}catch{return undefined}}
