import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {validateTrip,comparePlans,mergePlan,duration,totals,demoUpdate,warnings,emptyPersonal} from '../lib/trip.ts';
const p=JSON.parse(readFileSync(new URL('../data/plan.json',import.meta.url),'utf8'));
validateTrip(p);assert.equal(p.days.length,18);assert.equal(totals(p.expenses).states.paid.RUB,131397.6);assert.equal(totals(p.expenses).sums.EUR,854.27);assert.equal(totals(p.expenses,true).sums.EUR,914.27);assert.equal(totals(p.expenses).unknown,10);
const d=demoUpdate(p);assert.equal(d.newTime,'12:30');assert.equal(d.added,1);assert.equal(d.photoSaved,true);assert.ok(d.noteSaved);assert.equal(p.visits.find(v=>v.placeId==='nemo').start,'12:00');
const bad=structuredClone(p);bad.visits.push(bad.visits[0]);assert.throws(()=>validateTrip(bad));
const next=structuredClone(p);const v=next.visits.find(v=>v.placeId==='nemo');v.start='12:30';assert.equal(comparePlans(p,next,{visits:{[v.id]:{start:'13:00'}},checks:{}}).find(c=>c.id===v.id).conflict,true);
assert.equal(duration('23:00','01:00'),120);assert.equal((Date.parse(p.transfers[0].arrival)-Date.parse(p.transfers[0].departure))/60000,215);
assert.ok(warnings([{title:'A',start:'12:00',end:'14:00',category:'sight'},{title:'B',start:'13:00',end:'15:00',category:'sight'}]).length);
const source=JSON.stringify(p);assert.ok(!/Akazienweg|дата рождения|1982-03-12/.test(source));
console.log(JSON.stringify({result:'passed',days:p.days.length,visits:p.visits.length,paidRUB:131397.6,knownEUR:854.27,unknown:10,demo:d},null,2));
