import assert from 'node:assert/strict';
import {dayWeatherTargets,historicalDate,chooseWeather,loadCityWeather} from '../lib/weather.ts';
import fs from 'node:fs';
const plan=JSON.parse(fs.readFileSync('data/plan.json','utf8'));
const city=(date:string)=>dayWeatherTargets(plan,plan.days.find((d:any)=>d.date===date)).map(t=>t.city);
assert.deepEqual(city('2026-09-17'),['moscow']);
assert.deepEqual(city('2026-09-18'),['yerevan']);
assert.deepEqual(city('2026-09-19'),['yerevan']);
assert.deepEqual(city('2026-10-04'),['istanbul','moscow']);
assert.deepEqual(city('2026-09-23'),['dormagen','bergamo','cologne']);
assert.equal(historicalDate('2026-10-04','2026-09-07'),'2025-10-04');
assert.equal(historicalDate('2028-02-29','2028-01-01'),'2027-02-28');
assert.equal(historicalDate('2026-09-01','2026-09-07'),'2025-09-01');
const target=dayWeatherTargets(plan,plan.days[0])[0],now=Date.parse('2026-09-07T12:00:00Z');
const data=(date:string,max:number|null=22)=>({daily:{time:[date],weather_code:[0],temperature_2m_min:[12],temperature_2m_max:[max],precipitation_sum:[0],wind_speed_10m_max:[10]}});
assert.equal(chooseWeather(target,data(target.date),data('2025-09-17'),now).kind,'forecast');
assert.equal(chooseWeather(target,data(target.date,null),data('2025-09-17'),now).kind,'reference');
assert.equal(chooseWeather(target,data(target.date),data('2025-09-17'),now,now-3600001).kind,'reference');
assert.equal(chooseWeather(target,undefined,undefined,now).kind,'unavailable');
let count=0;globalThis.fetch=(async()=>{count++;return new Response(null,{status:503})}) as typeof fetch;
const failed=await loadCityWeather([target],now);assert.equal(failed[0].kind,'unavailable');assert.equal(count,2);
console.log('Weather checks passed: dates, overnight transfers, forecast priority, null values, expiry, leap day and network failure.');
